package com.blog.hbm.pojo;
// Generated Mar 25, 2015 5:41:45 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Time generated by hbm2java
 */
@Entity
@Table(name="time"
    ,catalog="timemanagement"
)
public class Time  implements java.io.Serializable {


     private Integer timeId;
     private Date time;

    public Time() {
    }

    public Time(Date time) {
       this.time = time;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="timeId", unique=true, nullable=false)
    public Integer getTimeId() {
        return this.timeId;
    }
    
    public void setTimeId(Integer timeId) {
        this.timeId = timeId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="time", nullable=false, length=10)
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


